modbusd: /home/travis/build/taka-wang/modbusd/json/cJSON_Utils.c File Reference
cJSON_Utils.c File Reference
#include <ctype.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "cJSON_Utils.h"
Functions
char * cJSONUtils_FindPointerFromObjectTo (cJSON *object, cJSON *target)
cJSON * cJSONUtils_GetPointer (cJSON *object, const char *pointer)
int cJSONUtils_ApplyPatches (cJSON *object, cJSON *patches)
void cJSONUtils_AddPatchToArray (cJSON *array, const char *op, const char *path, cJSON *val)
cJSON * cJSONUtils_GeneratePatches (cJSON *from, cJSON *to)
void cJSONUtils_SortObject (cJSON *object)
cJSON * cJSONUtils_MergePatch (cJSON *target, cJSON *patch)
cJSON * cJSONUtils_GenerateMergePatch (cJSON *from, cJSON *to)
Function Documentation
void cJSONUtils_AddPatchToArray (cJSON * array, const char * op, const char * path, cJSON * val)
 {cJSONUtils_GeneratePatch(array,op,path,0,val);}
int cJSONUtils_ApplyPatches (cJSON * object, cJSON * patches)
References cJSON::child, cJSON_Array, cJSON::next, and cJSON::type.
 {
     int err;
     if (patches->type!=cJSON_Array) return 1;   /* malformed patches. */
     if (patches) patches=patches->child;
     while (patches)
     {
         if ((err=cJSONUtils_ApplyPatch(object,patches))) return err;
         patches=patches->next;
     }
     return 0;
 }
char* cJSONUtils_FindPointerFromObjectTo (cJSON * object, cJSON * target)
References cJSON::child, cJSON_Array, cJSON_Object, cJSONUtils_FindPointerFromObjectTo(), cJSON::next, and cJSON::string.
Referenced by cJSONUtils_FindPointerFromObjectTo().
 {
     int type=object->type,c=0;cJSON *obj=0;
     if (object==target) return strdup("");
     for (obj=object->child;obj;obj=obj->next,c++)
     {
         char *found=cJSONUtils_FindPointerFromObjectTo(obj,target);
         if (found)
         {
             if (type==cJSON_Array)
             {
                 char *ret=(char*)malloc(strlen(found)+23);
                 sprintf(ret,"/%d%s",c,found);
                 free(found);
                 return ret;
             }
             else if (type==cJSON_Object)
             {
                 char *ret=(char*)malloc(strlen(found)+cJSONUtils_PointerEncodedstrlen(obj->string)+2);
                 *ret='/';cJSONUtils_PointerEncodedstrcpy(ret+1,obj->string);
                 strcat(ret,found);
                 free(found);
                 return ret;
             }
             free(found);
             return 0;
         }
     }
     return 0;
 }
cJSON* cJSONUtils_GenerateMergePatch (cJSON * from, cJSON * to)
References cJSON::child, cJSON_AddItemToObject(), cJSON_CreateNull(), cJSON_CreateObject(), cJSON_Delete(), cJSON_Duplicate(), cJSON_Object, cJSONUtils_GenerateMergePatch(), cJSONUtils_SortObject(), cJSON::next, cJSON::string, and cJSON::type.
Referenced by cJSONUtils_GenerateMergePatch().
 {
     cJSON *patch=0;
     if (!to) return cJSON_CreateNull();
     if (to->type!=cJSON_Object || !from || from->type!=cJSON_Object) return cJSON_Duplicate(to,1);
     cJSONUtils_SortObject(from);
     cJSONUtils_SortObject(to);
     from=from->child;to=to->child;
     patch=cJSON_CreateObject();
     while (from || to)
     {
         int compare=from?(to?strcmp(from->string,to->string):-1):1;
         if (compare<0)
         {
             cJSON_AddItemToObject(patch,from->string,cJSON_CreateNull());
             from=from->next;
         }
         else if (compare>0)
         {
             cJSON_AddItemToObject(patch,to->string,cJSON_Duplicate(to,1));
             to=to->next;
         }
         else
         {
             if (cJSONUtils_Compare(from,to)) cJSON_AddItemToObject(patch,to->string,cJSONUtils_GenerateMergePatch(from,to));
             from=from->next;to=to->next;
         }
     }
     if (!patch->child) {cJSON_Delete(patch);return 0;}
     return patch;
 }
cJSON* cJSONUtils_GeneratePatches (cJSON * from, cJSON * to)
References cJSON_CreateArray().
 {
     cJSON *patches=cJSON_CreateArray();
     cJSONUtils_CompareToPatch(patches,"",from,to);
     return patches;
 }
cJSON* cJSONUtils_GetPointer (cJSON * object, const char * pointer)
References cJSON_Array, cJSON_GetArrayItem(), cJSON_Object, cJSON::string, and cJSON::type.
 {
     while (*pointer++=='/' && object)
     {
         if (object->type==cJSON_Array)
         {
             int which=0; while (*pointer>='0' && *pointer<='9') which=(10*which) + *pointer++ - '0';
             if (*pointer && *pointer!='/') return 0;
             object=cJSON_GetArrayItem(object,which);
         }
         else if (object->type==cJSON_Object)
         {
             object=object->child;   while (object && cJSONUtils_Pstrcasecmp(object->string,pointer)) object=object->next;   /* GetObjectItem. */
             while (*pointer && *pointer!='/') pointer++;
         }
         else return 0;
     }
     return object;
 }
cJSON* cJSONUtils_MergePatch (cJSON * target, cJSON * patch)
References cJSON::child, cJSON_AddItemToObject(), cJSON_CreateObject(), cJSON_Delete(), cJSON_DeleteItemFromObject(), cJSON_DetachItemFromObject(), cJSON_Duplicate(), cJSON_NULL, cJSON_Object, cJSONUtils_MergePatch(), cJSON::next, cJSON::string, and cJSON::type.
Referenced by cJSONUtils_MergePatch().
 {
     if (!patch || patch->type != cJSON_Object) {cJSON_Delete(target);return cJSON_Duplicate(patch,1);}
     if (!target || target->type != cJSON_Object) {cJSON_Delete(target);target=cJSON_CreateObject();}
     patch=patch->child;
     while (patch)
     {
         if (patch->type == cJSON_NULL) cJSON_DeleteItemFromObject(target,patch->string);
         else
         {
             cJSON *replaceme=cJSON_DetachItemFromObject(target,patch->string);
             cJSON_AddItemToObject(target,patch->string,cJSONUtils_MergePatch(replaceme,patch));
         }
         patch=patch->next;
     }
     return target;
 }
void cJSONUtils_SortObject (cJSON * object)
References cJSON::child.
Referenced by cJSONUtils_GenerateMergePatch().
 {object->child=cJSONUtils_SortList(object->child);}