modbusd: /home/travis/build/taka-wang/modbusd/json.c File Reference
/home/travis/build/taka-wang/modbusd/json.c File Reference
cJSON utility wrapper header
#include <stdio.h>
#include <stdlib.h>
#include "json.h"
Functions
char * json_get_char (cJSON *inJson, const char *key)
Get char string via key from cJSON object.
int json_get_int (cJSON *inJson, const char *key)
Get int via key from cJSON object.
int file_to_json (const char *fname, cJSON **outJson)
Load json file to cJSON.
int json_to_file (const char *fname, cJSON *inJson)
Save cJSON to json file.
void json_release (cJSON *inJson)
Release cJSON root (auto mode)
Detailed Description
cJSON utility wrapper header
Author
taka-wang
Function Documentation
int file_to_json (const char * fname, cJSON ** outJson)
Load json file to cJSON.
Parameters
fname File name string.
outJson Pointer to cJSON output object.
Returns
Success or not.
References cJSON_Parse().
 {
     FILE *fPtr = fopen(fname,"rb");
     if (fPtr)
     {
         fseek(fPtr, 0, SEEK_END);
         long len = ftell(fPtr);
         fseek(fPtr, 0, SEEK_SET);
         char *data = (char*) malloc (len+1);
         int _ = fread(data, 1, len, fPtr); _=_;
         fclose(fPtr);
         *outJson = cJSON_Parse(data);
         free(data);
         return outJson ? 0 : 1;
     }
     else
     {
         return -1;
     }
 }
char* json_get_char (cJSON * inJson, const char * key)
Get char string via key from cJSON object.
Parameters
inJson cJSON object.
key Json key.
Returns
Char string.
References cJSON_GetObjectItem(), and cJSON::valuestring.
Referenced by main().
 {
     return cJSON_GetObjectItem(inJson, key)->valuestring;
 }
int json_get_int (cJSON * inJson, const char * key)
Get int via key from cJSON object.
Parameters
inJson cJSON object.
key Json key.
Returns
Integer.
References cJSON_GetObjectItem(), and cJSON::valueint.
Referenced by main(), and mbtcp_cmd_hanlder().
 {
     return cJSON_GetObjectItem(inJson, key)->valueint;
 }
void json_release (cJSON * inJson)
Release cJSON root (auto mode)
Parameters
inJson cJSON input object.
Returns
Void.
References cJSON_Delete().
 {
     cJSON_Delete(inJson);
 }
int json_to_file (const char * fname, cJSON * inJson)
Save cJSON to json file.
Parameters
fname File name string.
inJson cJSON input object.
Returns
Success or not.
References cJSON_Print().
 {
     FILE *fPtr = fopen(fname, "w");
     if (fPtr)
     {
         fprintf(fPtr, "%s", cJSON_Print(inJson));
         fclose(fPtr);
         return 0;
     }
     else
     {
         return -1;
     }
 }